default_agent: graph_rag_agent
agents:
  graph_rag_agent:
    name: graph_rag_agent
    entrypoint: C:/Users/lgspa/Downloads/AWS/graph-rag-agentcore/runtime_app.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: C:\Users\lgspa\Downloads\AWS\graph-rag-agentcore
    aws:
      execution_role: arn:aws:iam::762233739050:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-f627687020
      execution_role_auto_create: false
      account: '762233739050'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-762233739050-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: graph_rag_agent-SZQjF8B3yJ
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:762233739050:runtime/graph_rag_agent-SZQjF8B3yJ
      agent_session_id: bcb20b36-ac50-44ab-818c-d9a05233f048
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: graph_rag_agent_mem-1SmFLNCi4x
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:762233739050:memory/graph_rag_agent_mem-1SmFLNCi4x
      memory_name: graph_rag_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload:
        name: graph-rag-workload-identity
        arn: arn:aws:bedrock-agentcore:us-east-1:762233739050:workload-identity-directory/default/workload-identity/graph-rag-workload-identity
        return_urls: []
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
